#!/bin/bash
#makes global variable for trash
#will be placed in directory
#depending on username
#-p flag creates directory only if
#it does not exist
export TRASH=/home/$USER/146/trash
mkdir -p "$TRASH"
#for all files in trash folder it
#will permanently remove them
#including (sub)directories
rm -r $TRASH/*
